"""Add URL Model

Revision ID: b115c0352966
Revises: 4cab6fd22890
Create Date: 2023-02-19 16:28:24.380470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b115c0352966"
down_revision = "4cab6fd22890"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("target_url", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_urls_key"), "urls", ["key"], unique=True)
    op.create_index(
        op.f("ix_urls_target_url"), "urls", ["target_url"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_urls_target_url"), table_name="urls")
    op.drop_index(op.f("ix_urls_key"), table_name="urls")
    op.drop_table("urls")
    # ### end Alembic commands ###
