"""url.key should be non-nullable

Revision ID: 9bf24646431f
Revises: b115c0352966
Create Date: 2023-02-19 16:30:01.637457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9bf24646431f"
down_revision = "b115c0352966"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("urls", "key", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("urls", "key", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
